version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: first_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

